# Generated by Django 5.2.1 on 2025-07-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0002_role_servicetimes_person_roster_availability'),
        ('small_app', '0002_roles_persons'),
    ]

    operations = [
    ]
