# Generated by Django 5.2.1 on 2025-07-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0003_merge_20250702_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='assisstant_producer',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='producer',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='ServiceTimes',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
