# Generated by Django 5.2.1 on 2025-07-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0004_remove_person_roles_remove_person_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_special_role',
            field=models.BooleanField(default=False),
        ),
    ]
