# Generated by Django 5.2.1 on 2025-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0005_roles_is_special_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='role',
        ),
        migrations.AddField(
            model_name='persons',
            name='roles',
            field=models.ManyToManyField(blank=True, to='small_app.roles'),
        ),
    ]
