# Generated by Django 5.2.1 on 2025-07-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0007_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rosters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.persons')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.services')),
            ],
            options={
                'unique_together': {('person', 'service')},
            },
        ),
    ]
