# Generated by Django 5.2.1 on 2025-07-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0008_rosters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.persons')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.roles')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.rosters')),
                ('service_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('preferred', 'Preferred'), ('unavailable', 'Unavailable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.persons')),
                ('service_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_app.services')),
            ],
            options={
                'unique_together': {('person', 'service_time', 'date')},
            },
        ),
    ]
