# Generated by Django 5.2.1 on 2025-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0009_assignment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosters',
            name='date',
            field=models.DateField(default='2025-01-02'),
            preserve_default=False,
        ),
    ]
