# Generated by Django 5.2.1 on 2025-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0011_alter_rosters_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosters',
            name='date',
            field=models.DateField(),
        ),
    ]
