# Generated by Django 5.2.1 on 2025-07-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0012_alter_rosters_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='service_time',
        ),
        migrations.AddField(
            model_name='persons',
            name='is_assistant_producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='small_app.rosters'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('person', 'roster'), name='unique_assignment_per_person_per_service'),
        ),
    ]
