# Generated by Django 5.2.1 on 2025-07-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0013_remove_assignment_service_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='time',
        ),
    ]
