# Generated by Django 5.2.1 on 2025-07-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0014_rename_name_services_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('person', 'date')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='service_time',
        ),
    ]
