# Generated by Django 5.2.1 on 2025-07-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0015_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
