# Generated by Django 5.2.1 on 2025-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0016_alter_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
