# Generated by Django 6.0.5 on 2026-05-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0017_persons_is_present_delete_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembersBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('number_of_records', models.IntegerField(default=0)),
                ('success_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment_per_person_per_service',
        ),
        migrations.AddField(
            model_name='persons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='max_assignments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('person', 'roster', 'role'), name='unique_assignment_per_person_per_role_per_roster'),
        ),
        migrations.AddField(
            model_name='award',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='small_app.persons'),
        ),
        migrations.AddField(
            model_name='award',
            name='award_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='small_app.awardtype'),
        ),
        migrations.AddField(
            model_name='award',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='small_app.events'),
        ),
        migrations.AlterUniqueTogether(
            name='rosters',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rosters',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='small_app.events'),
        ),
        migrations.AlterUniqueTogether(
            name='rosters',
            unique_together={('event', 'date')},
        ),
        migrations.AddField(
            model_name='rosterfeedback',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='small_app.persons'),
        ),
        migrations.AddField(
            model_name='rosterfeedback',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='small_app.rosters'),
        ),
        migrations.RemoveField(
            model_name='rosters',
            name='person',
        ),
        migrations.RemoveField(
            model_name='rosters',
            name='service',
        ),
        migrations.AddConstraint(
            model_name='rosterfeedback',
            constraint=models.UniqueConstraint(fields=('roster', 'person'), name='unique_feedback_per_person_per_roster'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
