# Generated by Django 6.0.5 on 2026-05-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0018_award_awardtype_events_membersbulkupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterfeedback',
            name='feedback_category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('punctuality', 'Punctuality'), ('teamwork', 'Teamwork'), ('performance', 'Performance'), ('attitude', 'Attitude'), ('excellent', 'Excellent Service')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rosterfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MemberStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='small_app.persons')),
            ],
        ),
    ]
