# Generated by Django 6.0.5 on 2026-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0021_feedbacksharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='events', to='small_app.roles'),
        ),
    ]
