# Generated by Django 6.0.5 on 2026-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0022_events_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksharelink',
            name='global_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rosterfeedback',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
