# Generated by Django 6.0.5 on 2026-06-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0025_backfill_default_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='award',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='awardtype',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_types', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='awardtype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='events',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='feedbacksharelink',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_links', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='membersbulkupload',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='memberstreak',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_streaks', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='roles',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rosterfeedback',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_feedback', to='small_app.client'),
        ),
        migrations.AlterField(
            model_name='rosters',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='small_app.client'),
        ),
        migrations.AddConstraint(
            model_name='awardtype',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_award_type_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='persons',
            constraint=models.UniqueConstraint(fields=('client', 'email'), name='unique_person_email_per_client'),
        ),
        migrations.AddConstraint(
            model_name='roles',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_role_name_per_client'),
        ),
    ]
