# Generated by Django 6.0.5 on 2026-08-18 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0026_alter_assignment_client_alter_award_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login belonging to this person, if they have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('scheduler', 'Scheduler'), ('member', 'Member')], default='admin', help_text='What this user may do within their client.', max_length=20),
        ),
    ]
