# Generated by Django 6.0.5 on 2026-08-20 08:38

from django.db import migrations, models


def seed_display_order(apps, schema_editor):
    """Give existing roles a distinct position instead of leaving them all at 0.

    Seeded per client in the order they were already displayed in (name), so the
    arrangement admins see straight after the upgrade is the one they had before —
    they then drag from there.
    """
    Roles = apps.get_model('small_app', 'Roles')
    client_ids = Roles.objects.values_list('client_id', flat=True).distinct()
    for client_id in client_ids:
        roles = Roles.objects.filter(client_id=client_id).order_by('name', 'pk')
        for position, role in enumerate(roles):
            role.display_order = position
            role.save(update_fields=['display_order'])


def unseed_display_order(apps, schema_editor):
    """No-op: the column is dropped on the way back down."""


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0028_backfill_roles_and_person_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='roles',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the roster and PDF. Lower comes first.'),
        ),
        migrations.AddField(
            model_name='roles',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive roles are skipped when generating new rosters.'),
        ),
        migrations.RunPython(seed_display_order, unseed_display_order),
    ]
