# Generated by Django 6.0.5 on 2026-08-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0029_alter_roles_options_roles_display_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Saved row position within its band. Lower comes first.'),
        ),
    ]
