# Generated by Django 6.0.5 on 2026-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0030_alter_assignment_options_assignment_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterfeedback',
            name='feedback_category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('punctuality', 'Punctuality'), ('teamwork', 'Teamwork'), ('performance', 'Performance'), ('attitude', 'Attitude'), ('excellent', 'Excellence')], max_length=50, null=True),
        ),
    ]
