stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "small_backend.settings"
  PYTHONUNBUFFERED: "1"

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py migrate
    - python manage.py test
